### PR TITLE
Add init, remote-config in etc, add Makefile wrapper to goxc

### LINKED ISSUE #4: Long-running deployment?
- After you start it with `./slsnif /dev/ttySP2 -x | ./lutron-spy &`, is there a better way to stop it than `kill -9`ing the processes?
- Any thoughts on setting up an `init.d` files for autostart?

### PR DESCRIPTION
**Pull request by evq**
This should resolve #4, also offers `make install` target in preparation for #5. @JustinAiken if you get a chance can you test out that this works on your hub? Everything came up fine after a reboot on mine. It's a bit hacky imo (specifically the use of killall), but it's in the same style as the existing ones :)

### CODE REVIEW

**Comment by JustinAiken** [comment]
Hmm, was hoping something added in the `goxc.json` would fix the compile for me, but I still get the `Illegal instruction` error... could you post the latest bin, and I'll try moving my remote-config.json to the new location?

**Comment by evq** [comment]
Good news, I've managed to reproduce your error during cross compilation! :P

I did save a copy of the binary before I messed with my go environment, so [give this a try.](http://dropcanvas.com/u3cfv)

**Comment by evq** [comment]
Hey @JustinAiken,

I figured out the `Illegal Instruction` issue. Turns out when goxc builds the go cross compilation toolchain it doesn't use the settings for the xc (cross compile) task that are specified in .goxc.json. It instead uses the settings from the toolchain task :) I've updated .goxc.json, if you do the following your env should be good to go.

``` bash
# wipe out existing cross compile toolchain
brew remove go
brew install go
make
```

**Comment by JustinAiken** [comment]
Sweet! That works - both the rebuilding of the go toolchain, and the init script.

**Comment by evq** [comment]
:)

**Pull request merged**
